name: "Airplay 2 for Home Assistant"
description: "Adds Airplay 2 capabilities to Home Assistant"
url: https://github.com/alxw/JohannVRs-Home-Assistant-Addons/tree/main/Airplay2
version: "0.1.0"
slug: "airplay2"
init: false
arch:
  - aarch64
  - amd64
  - armv7
boot: "auto"
host_network: true
audio: true
options:
  airplay_name: "Hass.io"
  offset: "0.0"
  enabled: "no"
  mqtt_host: "core-mosquitto"
  mqtt_username: "user"
  mqtt_password: "password"
  mqtt_publish_cover: "no"
  ignore_volume_control: "no"
schema:
  airplay_name: str
  offset: str
  enabled: str
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
  mqtt_publish_cover: str
  ignore_volume_control: str
image: "johannvr/ha-airplay2-{arch}-debian"
